import { Metadata } from "next";
import HomePage from "./home/page";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <HomePage />
    </>
  );
}
